In [2]:
import numpy as np
a=np.array([1,2,3])
print(a)
b=np.array([[1,2,3],[4,5,6]])
print(b)
c=np.zeros((3,4))
print(c)
d=np.ones((2,2))
print(d)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]]


In [4]:
a1=np.array([1,2,3])
b1=np.array([4,5,6])
c1=a1+b1
print(c1)
d1=np.array([[1,2],[3,4]])
e1=np.array([[5,6],[7,8]])
f1=d1*e1
print(f1)
g1=np.array([[1,2],[3,4]])
h1=np.array([[5,6],[7,8]])
i1=np.dot(g1,h1)
print(i1)

[5 7 9]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
